module.exports = {
  apps: [
    {
      name: 'bublee',
      script: '/home/ubuntu/bublee/run.sh',
      cwd: '/home/ubuntu/bublee',
      restart_delay: 3000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '30s',
      max_memory_restart: '1G',
      kill_timeout: 5000,
      time: true,
      env: { PYTHONUNBUFFERED: '1' },
      out_file: '/home/ubuntu/bublee/logs/bublee.log',
      error_file: '/home/ubuntu/bublee/logs/bublee-error.log',
      watch: false,
    },
    {
      name: 'bublee-clinica-de-las-americas',
      script: '/home/ubuntu/bublee/instances/clinica-de-las-americas/run.sh',
      cwd: '/home/ubuntu/bublee/instances/clinica-de-las-americas',
      restart_delay: 3000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '30s',
      max_memory_restart: '1G',
      kill_timeout: 5000,
      time: true,
      env: { PYTHONUNBUFFERED: '1' },
      out_file: '/home/ubuntu/bublee/instances/clinica-de-las-americas/logs/bublee.log',
      error_file: '/home/ubuntu/bublee/instances/clinica-de-las-americas/logs/error.log',
      watch: false,
    },
    {
      name: 'bublee-ovni',
      script: '/home/ubuntu/bublee/agents/ovni/run.sh',
      cwd: '/home/ubuntu/bublee/agents/ovni',
      restart_delay: 3000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '30s',
      max_memory_restart: '1G',
      kill_timeout: 5000,
      time: true,
      env: { PYTHONUNBUFFERED: '1' },
      out_file: '/home/ubuntu/bublee/agents/ovni/logs/bublee.log',
      error_file: '/home/ubuntu/bublee/agents/ovni/logs/error.log',
      watch: false,
    },
  ]
};
